name: Daily Basketball Predictions

on:
  schedule:
    # Run every day at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run predictions
      env:
        API_BASKETBALL_KEY: ${{ secrets.API_BASKETBALL_KEY }}
      run: |
        python predict_matches.py
    
    - name: Commit and push predictions
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add predictions/
        git diff --quiet && git diff --staged --quiet || (git commit -m "🏀 Daily predictions - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
